# Please don't modify this file, without first checking if it makes sense to
# adopt for most other Kapost projects. Ideally, we would keep these files as
# similar as possible to ease maintainability. Instead, open a PR in the
# codeclimate-common repo at https://github.com/kapost/codeclimate-common

---
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
    exclude_paths:
      - "spec/"
  reek:
    enabled: true
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true

ratings:
  paths:
    - app/**
    - lib/**
    - "**/*.rb"

exclude_paths:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
  - "spec/fixtures/**/*"


