version: 2
jobs:
  build:
    working_directory: ~/kapost_deploy
    docker:
      - image: kapost/ruby:2.4.2-node-6.11.5
    steps:
      - checkout
      - run: bundle install
      - run:
          name: install cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: |
            bundle exec rake
            ./cc-test-reporter after-build --exit-code $?
